name: genipa-seed-digital-phenotyping
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - statsmodels
  - pip
  - pip:
      - opencv-python
